export const ATTRACTION_DATA_LOAD = 'ATTRACTION_DATA_LOAD';
export const ATTRACTION_DATA_LOADING = 'ATTRACTION_DATA_LOADING';
export const ATTRACTION_DATA_LOADED = 'ATTRACTION_DATA_LOADED';

export const ATTRACTION_DETAIL_FETCH = 'ATTRACTION_DETAIL_FETCH';